markdown: kramdown
paginate: 5
folder: /jekyll
permalink: '/jekyll/:year/:month/:day/:title/'

# Need this hack to work with the wordpressdotcom.rb imported
# WP posts.
textile_ext: textile

domain: aws.saicharan.in
email: me@saicharan.in
title: Sai Charan
tagline: A Celebration called Life!
author: Sai Charan

disqus:
  name: scharan

feedburner:
  feedburnerid: scharan

google:
  analytics-id: UA-810922-4

