markdown: rdiscount
paginate: 5
folder: /blog
permalink: '/blog/:year/:month/:day/:title/'

# Need this hack to work with the wordpressdotcom.rb imported
# WP posts.
textile_ext: textile

domain: www.saicharan.in
email: me@saicharan.in
title: Sai Charan
tagline: A Celebration called Life!
author: Sai Charan

disqus:
  name: scharan

feedburner:
  feedburnerid: scharan

google:
  analytics-id: UA-810922-4
  plus-id: 111168674571731850317

facebook: 
  appid: 661786726

twitter: 
  id: scharan

asset_bundler:
  compress:
    js: false #yui-compressor -o :outfile :infile
    css: false #yui-compressor -o :outfile :infile
  base_path: /css/
  server_url:
  remove_bundled: false
  dev: false
  markup_templates:
    js: "<script async type='text/javascript' src='{{url}}'></script>\n"
    css: "<link rel='stylesheet' type='text/css' href='{{url}}' />\n"

