application: sai-static
version: 1
runtime: python27
api_version: 1
threadsafe: no

# http://stackoverflow.com/a/3722135/162471
error_handlers:
- file: /404.html

handlers:
- url: /
  static_files: index.html
  upload: index.html

- url: /(.*\.(gif|png|jpg|ico|js|css|asc|html|txt|textile|xml))
  static_files: \1
  upload: (.*\.(gif|png|jpg|ico|js|css|asc|html|txt|textile|xml))

# http://stackoverflow.com/a/6566464/162471
- url: /(.*)/
  static_files: \1/index.html
  upload: .*/index\.html

- url: /robots.txt
  static_files: robots.txt
  upload: robots.txt 

- url: /.*
  static_files: 404.html
  upload: 404.html

#- url: .*
#  script: main.py

