application: sai-static
version: 1
runtime: python27
api_version: 1
threadsafe: no

handlers:
- url: /
  static_files: index.html
  upload: index.html

- url: /(.*\.(gif|png|jpg|ico|js|css|asc|html|txt|textile|xml))
  static_files: \1
  upload: (.*\.(gif|png|jpg|ico|js|css|asc|html|txt|textile|xml))

- url: /robots.txt
  static_files: robots.txt
  upload: robots.txt 

#- url: .*
#  script: main.py

